name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  publish-cargo:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  update-homebrew:
    needs: publish-cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: bannawandoor27/homebrew-commitgenius
          token: ${{ secrets.GH_PAT }}
      - name: Update Formula
        run: |
          version=${GITHUB_REF#refs/tags/v}
          sha=$(curl -L "https://github.com/bannawandoor27/Commitgenius/archive/refs/tags/v${version}.tar.gz" | shasum -a 256 | cut -d ' ' -f 1)
          sed -i "s/REPLACE_AFTER_RELEASE/${sha}/" Formula/commitgenius.rb
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Formula/commitgenius.rb
          git commit -m "Update commitgenius to ${version}"
          git push
